### ISSUE TITLE
Update `postcss-preset-env`

### ISSUE THREAD

**Issue by boris-petrov** [webark/ember-cli-styles#11]
Currently `ember-cli-style` uses `postcss-preset-env` version [6.7.0](https://github.com/webark/ember-cli-styles/blob/ember-cli-styles-preprocessor%401.0.0-alpha.3/packages/preprocessor/package.json#L43). It would be nice to upgrade to [7.3.1+](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env). That way PostCSS 8 could be used throughout so PostCSS versions are not mixed when users use version 8.

**Comment by webark** [comment]
Ok. I can look into this part.

**Comment by webark** [comment]
closed by #16
