### ISSUE TITLE
Route support

### ISSUE THREAD

**Issue by btecu** [webark/ember-cli-styles#17]
`ember-component-css` supported not just components but also routes (pods only).
Could we get _standard_ routes (templates) support?

**Comment by webark** [comment]
This should be working. There's a test case for this. You will have to add the `this.routeStyleNamespaceClassSet` from the application controller (easiest way to handle this).

**Comment by btecu** [comment]
That's great! I haven't tried the project yet, I'm waiting on the documentation.

**Comment by webark** [comment]
ha! yea… :/ sorry about the delay with that.
