### ISSUE TITLE
classnameBindings won't work in glimmer

### ISSUE THREAD

**Issue by BryanCrotaz** [webark/ember-cli-styles#22]
In component-style:
```js
       if (!component.classNameBindings.includes('styleNamespace')) {
          proto.classNameBindings =
            component.classNameBindings.concat('styleNamespace');
        }
```
If this is a glimmer component, won't `component.classNameBindings` be undefined?

**Comment by webark** [comment]
It would be yes. This functionality also got removed from being included in the initializer, and classic components will now no longer be namespaced by default as there is no good reliable way.

**Comment by webark** [comment]
removed this file to not confuse people
